# Generated by Django 4.2.1 on 2023-05-24 08:29

from django.db import migrations, models

import json_array_field.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JSONArrayFieldModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("list_field", json_array_field.db.fields.JSONArrayField(default=list)),
            ],
        ),
    ]
